### ISSUE TITLE
Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.

### ISSUE THREAD

**Issue by lol768** [cayasso/mongo-live#1]
```
/usr/lib/node_modules/mongo-live/node_modules/mongo-watch/node_modules/coffee-script/lib/coffee-script/coffee-script.js:213
          throw new Error("Use CoffeeScript.register() or require the coffee-s
                ^
Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.
  at Object.base.(anonymous function) [as .coffee] (/usr/lib/node_modules/mongo-live/node_modules/mongo-watch/node_modules/coffee-script/lib/coffee-script/coffee-script.js:213:17)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/lib/node_modules/mongo-live/node_modules/mongo-watch/index.js:2:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/lib/node_modules/mongo-live/lib/index.js:5:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/lib/node_modules/mongo-live/index.js:1:80)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/tmp/mongo.js:1:79)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:935:3
```

**Comment by lol768** [comment]
Seems adding `var cs = require("coffee-script/register");` to the top of my script fixes things. Might be worth updating docs?

**Comment by lemonbuzz** [comment]
I had the same issue and your solution fixed it. However I am now getting this error:


```
MongoLive/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

TypeError: stream.on is not a function
```

**Comment by cayasso** [comment]
@lemonbuzz Sorry this lib is deprecated in favor of `mongo-oplog` https://github.com/cayasso/mongo-oplog which is a more robust solution.
Hope it works for your need.
Cheers!

**Comment by lol768** [comment]
Closing this since it seems the repo is now obsolete and I can't actually remember what this did.
